name = "SXTMerger"
uuid = "05795ded-2e6b-4fe1-8ca7-69dda6a83a16"
authors = ["Gulab Dewangan <gulabd@iucaa.in>"]
version = "1.1.0"

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"

[compat]
CFITSIO = "1.4.0"
DataFrames = "1.2"
FITSIO = "0.15"
julia = "1.6.3"
